# very simple makefile
# top down 

HW03 : burak_tekdamar_161044115.o
	g++ -o 161044115 burak_tekdamar_161044115.o

main.o : burak_tekdamar_161044115.cpp
	g++ -c -std=c++11x -Wall burak_tekdamar_161044115.cpp

clean:
	rm *.o HW03
